name: MaxStackSize
author: Fjc
main: maxstacksize.main
version: 1.0
api-version: 1.16

commands:
  maxstacksize:
    aliases: [mss, maxstack]
    description: Change the maximum stack size of any item.

permissions:
  maxstacksize.reload
    default: op
  maxstacksize.modify
    default: op
  maxstacksize.view
    default: true
    
    
  
  
